package Zihan;

import java.util.List;


/**
 * Validates a simulation
 */
public class Validate {
	private static class InvalidSimulationException extends Exception {
		public InvalidSimulationException() { }
	};

	// Helper method for validating the simulation
	private static void check(boolean check,
			String message) throws InvalidSimulationException {
		if (!check) {
			System.err.println("SIMULATION INVALID : "+message);
			throw new Validate.InvalidSimulationException();
		}
	}

	/** 
	 * Validates the given list of events is a valid simulation.
	 * Returns true if the simulation is valid, false otherwise.
	 *
	 * @param events - a list of events generated by the simulation
	 *   in the order they were generated.
	 *
	 * @returns res - whether the simulation was valid or not
	 */
	public static boolean validateSimulation(List<SimulationEvent> events) {
		try {
			check(events.get(0).event == SimulationEvent.EventType.SimulationStarting,
					"Simulation didn't start with initiation event");
			check(events.get(events.size()-1).event == 
					SimulationEvent.EventType.SimulationEnded,
					"Simulation didn't end with termination event");

			/* In hw3 you will write validation code for things such as:
				Should not have more eaters than specified
				Should not have more cooks than specified
				The coffee shop capacity should not be exceeded
				The capacity of each machine should not be exceeded
				Eater should not receive order until cook completes it
				Eater should not leave coffee shop until order is received
				Eater should not place more than one order
				Cook should not work on order before it is placed
			 */

//			check(events.get());
            System.out.println("****************************************************");
            System.out.println("Validation:");
            int ne = 0;
            for (SimulationEvent s: events) {
                if (s.event == SimulationEvent.EventType.CustomerStarting) {
                    ne++;
                }
            }
            System.out.println("Total Number of Eaters: " + ne);
            int nc = 0;
            for (SimulationEvent s: events) {
                if (s.event == SimulationEvent.EventType.CookStarting) {
                    nc++;
                }
            }
            System.out.println("Total Number of Cooks: " + nc);
            System.out.println("Check Eater Submit One Order: ");
            int os = 0;
            for (SimulationEvent s: events) {
                if (s.event == SimulationEvent.EventType.CustomerReceivedOrder) {
                    os++;
                }
            }
            System.out.println(os == ne);
            System.out.println("Check Receiving Order and Cook Completing Order: ");
            for (int j = 1; j < ne; j++) {
                System.out.println("Checking Eater " + j);
                int receivingindex = 0, completingindex = 0;
                for (int i = 0; i < events.size(); i++) {
                    if (events.get(i).event == SimulationEvent.EventType.CookCompletedOrder && events.get(i).orderNumber == j) {
                        completingindex = i;
                    }
                    if (events.get(i).event == SimulationEvent.EventType.CustomerReceivedOrder && events.get(i).orderNumber == j) {
                        receivingindex = i;
                    }
                }
                if (completingindex < receivingindex) {
                    System.out.println(true);
                }
                else {
                    System.out.println(false);
                }
            }

            System.out.println("Check Receiving Order and Leaving Coffee: ");
            for (int j = 1; j < ne; j++) {
                System.out.println("Checking Eater " + j);
                int receivingindex = 0, leavingindex = 0;
                for (int i = 0; i < events.size(); i++) {
                    if (events.get(i).event == SimulationEvent.EventType.CustomerReceivedOrder && events.get(i).orderNumber == j) {
                        receivingindex = i;
                    }
                    if (events.get(i).event == SimulationEvent.EventType.CustomerLeavingCoffeeShop && events.get(i).customer.getOrderNum() == j) {
                        leavingindex = i;
                    }
                }
                if (leavingindex > receivingindex) {
                    System.out.println(true);
                }
                else {
                    System.out.println(false);
                }
            }




			return true;
		} catch (InvalidSimulationException e) {
			return false;
		}
	}
}
